production: &default
  name: LittleWeb
  host: littleweb.herokuapp.com
  pusher:
    app_id: "<%= ENV['PUSHER_APP_ID'] %>"
    key: "<%= ENV['PUSHER_KEY'] %>"
    secret: "<%= ENV['PUSHER_SECRET'] %>"
   
development:
  <<: *default

test:
  <<: *default
